server:
  port: 9091

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      initializationFailTimeout: -1
      connectionTimeout: 60000
      maximumPoolSize: 5
      minimumIdle: 1
      idleTimeout: 300000
      keepaliveTime: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.finflow: DEBUG
    org.springframework: INFO
  file:
    name: /app/logs/auth-service.log
  logback:
    rollingpolicy:
      max-history: 7
      file-name-pattern: /app/logs/auth-service.%d{yyyy-MM-dd}.log

springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,tracing

security:
  jwt:
    secret: ${JWT_SECRET:mysecretkeymysecretkeymysecretkey12}
    issuer: ${JWT_ISSUER:finflow-auth}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
