server:
  port: 9091

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: capgdb
    password: capgdb
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/