sonar.projectKey=finflow
sonar.projectName=FinFlow
sonar.sourceEncoding=UTF-8

sonar.sources=auth-service/src/main,application-service/src/main,document-service/src/main,admin-service/src/main,api-gateway/src/main,eureka-server/src/main
sonar.tests=auth-service/src/test,application-service/src/test,document-service/src/test,admin-service/src/test,api-gateway/src/test
sonar.java.binaries=auth-service/target/classes,application-service/target/classes,document-service/target/classes,admin-service/target/classes,api-gateway/target/classes,eureka-server/target/classes
sonar.junit.reportPaths=auth-service/target/surefire-reports,application-service/target/surefire-reports,document-service/target/surefire-reports,admin-service/target/surefire-reports,api-gateway/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=auth-service/target/site/jacoco/jacoco.xml,application-service/target/site/jacoco/jacoco.xml,document-service/target/site/jacoco/jacoco.xml,admin-service/target/site/jacoco/jacoco.xml,api-gateway/target/site/jacoco/jacoco.xml,eureka-server/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/dist/**,frontend/**
