server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - name: JwtGatewayFilter

            - id: application-service
              uri: lb://APPLICATION-SERVICE
              predicates:
                - Path=/application/**
              filters:
                - name: JwtGatewayFilter

            - id: document-service
              uri: lb://DOCUMENT-SERVICE
              predicates:
                - Path=/document/**
              filters:
                - name: JwtGatewayFilter

            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/admin/**
              filters:
                - name: JwtGatewayFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
              - http://127.0.0.1:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.finflow: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework: INFO
  file:
    name: /app/logs/api-gateway.log
  logback:
    rollingpolicy:
      max-history: 7
      file-name-pattern: /app/logs/api-gateway.%d{yyyy-MM-dd}.log

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,tracing

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth-Service
        url: /auth/v3/api-docs
      - name: Application-Service
        url: /application/v3/api-docs
      - name: Document-Service
        url: /document/v3/api-docs
      - name: Admin-Service
        url: /admin/v3/api-docs
    operations-sorter: method
    tags-sorter: alpha
  gateway:
    discovery:
      enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:mysecretkeymysecretkeymysecretkey12}
    issuer: ${JWT_ISSUER:finflow-auth}
