server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        # 🔐 AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: JwtGatewayFilter

        # 📄 APPLICATION SERVICE
        - id: application-service
          uri: lb://APPLICATION-SERVICE
          predicates:
            - Path=/application/**
          filters:
            - name: JwtGatewayFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/